apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onursagir/argos-sandbox.git
    targetRevision: main
    path: manifests/main/hello
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    automated: {}
