apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onursagir/argos-sandbox.git
    targetRevision: main
    path: manifests/echo
  syncPolicy:
    automated: {}
